version: '3.1'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 55
      PGDATA: /data/postgres
      POSTGRES_DB: bidding
    ports:
      - "5432:5432"
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
